version: 'alpha-1.0'
services:
  frontend:
      container_name : lifetime-vis
      image: lifetime-visualizer:latest
      build:
        context: .
        target: dev
      restart: always
      command: npm run dev
      volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
      environment:
        - NODE_ENV=development
      ports:
        - 3000:3000
